<?php
// === FILE 1: Center Info (Sheet2) ===
// Headers: Organization/Center Name | School District | Center Address | Staff Count | Children Count | Technology Available | Center Leader Name | Center Leader Phone | Center Leader Email | Communication Preference | Liaison Name | Liaison Phone | Liaison Email

$center_info_headers = array (
  0 => '',
  1 => 'Organization/Center Name',
  2 => 'School District',
  3 => 'Center Address',
  4 => 'Total number of staff who will participate in the research assessment:',
  5 => 'Total number of children who will participate in the research assessment:',
  6 => 'Is classroom technology available for teachers to participate in the research assessment?',
  7 => 'Center Leader Name',
  8 => 'Center Leader Phone',
  9 => 'Center Leader Email',
  10 => 'Communication Preference',
  11 => 'Liaison Name',
  12 => 'Liaison Phone',
  13 => 'Liaison Email',
);

$center_info_data = array (
  0 => 
  array (
    0 => '',
    1 => 'South Bay Head Start/Early Head Start',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '990 US-27, South Bay, FL 33493',
    4 => '6',
    5 => '21',
    6 => 'Yes, laptop',
    7 => 'Francetine Inman-Dennard',
    8 => '561-574-3464',
    9 => 'francetine.inman@lsfnet.org',
    10 => 'Email',
    11 => 'Shirley Coney',
    12 => '561-983-9611',
    13 => 'shirley.coney@lsfnet.org',
  ),
  1 => 
  array (
    0 => '',
    1 => 'West Palm Beach Head Start/Early Head Start',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '100 S Chillingworth Dr, West Palm Beach, FL 33409',
    4 => '26',
    5 => '161',
    6 => 'Yes, laptop',
    7 => 'Gwendolyn Kelly',
    8 => '561-694-5462',
    9 => 'gwendolyn.kelly@lsfnet.org',
    10 => 'Email',
    11 => 'Josephine Mitchell & Josue Morin',
    12 => '561-779-3822',
    13 => 'josephine.mitchell@lsfnet.org',
  ),
  2 => 
  array (
    0 => '',
    1 => 'Jupiter Head Start',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '6415 W Indiantown Rd, Jupiter, FL 33458',
    4 => '7',
    5 => '62',
    6 => 'Yes, laptop',
    7 => 'Josephine Mitchell',
    8 => '561-779-3822',
    9 => 'josephine.mitchell@lsfnet.org',
    10 => 'Email',
    11 => 'Josephine Mitchell & Josue Morin',
    12 => '561-779-3822',
    13 => 'josephine.mitchell@lsfnet.org',
  ),
  3 => 
  array (
    0 => '',
    1 => 'Monica Turner Faimly Child Care Home',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '916 SW 12th St. Belle Glade, FL 33430',
    4 => '1',
    5 => '2',
    6 => 'Yes, laptop',
    7 => 'Monica Turner',
    8 => '561-596-8924',
    9 => 'MonicaT52@aol.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
  4 => 
  array (
    0 => '',
    1 => 'Patricia Oliver Family Child Care Home',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '311 W. 16th Way, Riviera beach, FL 33404',
    4 => '1',
    5 => '2',
    6 => 'Yes, laptop',
    7 => 'Patricia Oliver',
    8 => '561-788-9136',
    9 => 'Oliverfcc@yahoo.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
  5 => 
  array (
    0 => '',
    1 => 'Lisa\'s Lil Wonders Family Child Care Home',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '1551 W. 13th St, Riviera Beach, FL 33404',
    4 => '1',
    5 => '9',
    6 => 'Yes, laptop',
    7 => 'Lisa Dupree',
    8 => '561-574-0154',
    9 => 'Ladyd0316@yahoo.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
  6 => 
  array (
    0 => '',
    1 => 'Nichola Griffiths-Butts Family Child Care Home',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '180 NW 3rd Av. South Bay, FL 33493',
    4 => '1',
    5 => '9',
    6 => 'Yes, laptop',
    7 => 'Nichola Griffiths-Butts',
    8 => '561-506-4739',
    9 => 'Nicholagriffiths@yahoo.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
  7 => 
  array (
    0 => '',
    1 => 'Smart Kidz College Family Child Care Home',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '1140 W 35th St Riviera Beach, 33404',
    4 => '1',
    5 => '4',
    6 => 'Yes, laptop',
    7 => 'Loretta Ferguson',
    8 => '561-541-1660',
    9 => 'Smartkidzcollege@gmail.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
  8 => 
  array (
    0 => '',
    1 => 'Bear Necessities FCCH',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '1124 W 28th St, Riviera Beach, FL33404',
    4 => '1',
    5 => '2',
    6 => 'Yes, laptop',
    7 => 'Lashea Walker',
    8 => '561-574-3464',
    9 => 'Bearncty@yahoo.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
  9 => 
  array (
    0 => '',
    1 => 'Jessica Thurmond FCCH',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '194 E 30th Street Riviera Beach, FL33404',
    4 => '2',
    5 => '6',
    6 => 'Yes, laptop',
    7 => 'Jessica Thurmond',
    8 => '561-584-4550',
    9 => 'Jessicathurmond1@gmail.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
  10 => 
  array (
    0 => '',
    1 => 'My Precious Lillies Family Child Care Home',
    2 => 'Lutheran Services Florida- Palm Beach',
    3 => '3700 RJ Hendley Ave, Riviera Beach, 33404',
    4 => '1',
    5 => '5',
    6 => 'Yes, laptop',
    7 => 'Ezziola Jones',
    8 => '561-714-5158',
    9 => 'mypreciouslillieshccf@gmail.com',
    10 => 'Email',
    11 => 'Llenni Lopez',
    12 => '561-942-7357',
    13 => 'llenni.lopez@lsfnet.org',
  ),
);


// === FILE 2: Teacher Roster ===
// Headers: Center Name | Teacher Full Name | Role | Email | Classroom Name | Age Group

$teacher_roster_headers = array (
  0 => 'Center Name',
  1 => 'Teacher Full Name',
  2 => 'Role',
  3 => 'Email',
  4 => 'Classroom Name',
  5 => 'Age Group',
);

$teacher_roster_data = array (
  0 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Yanet Bello Santos',
    2 => 'ITS',
    3 => 'Yanet.bellosantos@lsfnet.org',
    4 => 'EHS A',
    5 => 'Infants',
  ),
  1 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Marta Soto',
    2 => 'ITS',
    3 => 'Marta.soto@lsfnet.org',
    4 => 'EHS A',
    5 => 'Infants',
  ),
  2 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Isbel Roa',
    2 => 'ITS',
    3 => 'Isbel.roa@lsfnet.org',
    4 => 'EHS B',
    5 => 'Toddlers',
  ),
  3 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ashley Bedward',
    2 => 'ITS',
    3 => 'Ashley.bedward@lsfnet.org',
    4 => 'EHS C',
    5 => '1 year olds',
  ),
  4 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Connie Epps',
    2 => 'ITS',
    3 => 'Connie.epps@lsfnet.org',
    4 => 'EHS D',
    5 => '1 year olds',
  ),
  5 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Mileidys Carvajal',
    2 => 'ITS',
    3 => 'Mileidys.carvajal@lsfnet.org',
    4 => 'EHS D',
    5 => '1 year olds',
  ),
  6 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Indra ramsaroop',
    2 => 'ITS',
    3 => 'Indra.ramsaroop@lsfnet.org',
    4 => 'EHS E',
    5 => '2 year olds',
  ),
  7 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Daimarelis Junco Cordero',
    2 => 'ITS',
    3 => 'Daimarelis.juncocordero@lsfnet.org',
    4 => 'EHS E',
    5 => '2 year olds',
  ),
  8 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Serena White',
    2 => 'ITS',
    3 => 'Setena.white@lsfnet.org',
    4 => 'EHS F',
    5 => '2 year olds',
  ),
  9 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Elianys Pedraza',
    2 => 'ITS',
    3 => 'Elianys.pedraza@lsfnet.org',
    4 => 'EHS F',
    5 => '2 year olds',
  ),
  10 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Latonya Perez',
    2 => 'ITS',
    3 => 'Latonya.perez@lsfnet.org',
    4 => 'EHS G',
    5 => '2 year old',
  ),
  11 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Carissa Nadeau',
    2 => 'ITS',
    3 => 'Carissa.nadeau@lsfnet.org',
    4 => 'EHS G',
    5 => '2 year old',
  ),
  12 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kenia Mas',
    2 => 'Teacher',
    3 => 'Kenia.mas@lsfnet.org',
    4 => 'HS A',
    5 => '3 year olds',
  ),
  13 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Sharon Leighton',
    2 => 'TA',
    3 => 'Sharon.leighton@lsfnet.org',
    4 => 'HS A',
    5 => '3 year olds',
  ),
  14 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Alina Bach Porro',
    2 => 'Teacher',
    3 => 'Alina.bachporro@lsfnet.org',
    4 => 'HS B',
    5 => '3year old',
  ),
  15 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jeandeline Delusme',
    2 => 'TA',
    3 => 'jeandeline.delusme@lsfnet.org',
    4 => 'HS B',
    5 => '3 year olds',
  ),
  16 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Cynthia Desty',
    2 => 'Teacher',
    3 => 'cynthia.desty@lsfnet.org',
    4 => 'HS C',
    5 => 'mixed',
  ),
  17 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Nakia Harp',
    2 => 'TA',
    3 => 'nakia.harp@lsfnet.org',
    4 => 'HS C',
    5 => 'mixed',
  ),
  18 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Shameka Byrd',
    2 => 'Teacher',
    3 => 'Shameka.byrd@lsfnet.org',
    4 => 'HS D',
    5 => 'VPK',
  ),
  19 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Nilay Veliz Padron',
    2 => 'TA',
    3 => 'Nilay.veliz@lsfnet.org',
    4 => 'HS D',
    5 => 'VPK',
  ),
  20 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Sangita Patel',
    2 => 'Teacher',
    3 => 'Sangita.patel@lsfnet.org',
    4 => 'HS E',
    5 => 'VPK',
  ),
  21 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Dunia Barreto',
    2 => 'TA',
    3 => 'dunia.barreto@lsfnet.org',
    4 => 'HS E',
    5 => 'VPK',
  ),
  22 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Gale Bethel',
    2 => 'Teacher',
    3 => 'gale.bethel@lsfnet.org',
    4 => 'HS F',
    5 => 'VPK',
  ),
  23 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kyesha Curtis',
    2 => 'TA',
    3 => 'Kyesha.curtis@lsfnet.org',
    4 => 'HS F',
    5 => 'VPK',
  ),
  24 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kelly Castro Vargas',
    2 => 'Teacher',
    3 => 'kelly.castro@lsfnet.org',
    4 => 'HS G',
    5 => '3 year olds',
  ),
  25 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Rachelle Louis',
    2 => 'Lead Teacher',
    3 => 'rachelle.louis1@lsfnet.org',
    4 => 'HS-A',
    5 => 'Preschool',
  ),
  26 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Ana Vilfort',
    2 => 'T Assitant',
    3 => 'ana.vilfort@lsfnet.org',
    4 => 'HS-A',
    5 => 'Preschool',
  ),
  27 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Guerline  Villiere',
    2 => 'Lead Teacher',
    3 => 'guerline.villiere@lsfnet.org',
    4 => 'HS-B',
    5 => 'Preschool',
  ),
  28 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Seritha Dilworth',
    2 => 'T Assistant',
    3 => 'seritha.dilworth@lsfnet.org',
    4 => 'HS-B',
    5 => 'Preschool',
  ),
  29 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Elva Engativa',
    2 => 'Lead Teacher',
    3 => 'elva.engativa@lsfnet.org',
    4 => 'HS-C',
    5 => 'Preschool',
  ),
  30 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Luz Bello',
    2 => 'T Assistant',
    3 => 'luz.bellosilverio@lsfnet.org',
    4 => 'HS-C',
    5 => 'Preschool',
  ),
  31 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Cynthia Graham',
    2 => 'T Assistant',
    3 => 'cynthia.graham@lsfnet.org',
    4 => 'HS-D',
    5 => 'Preschool',
  ),
  32 => 
  array (
    0 => 'Monica Turner FCCH',
    1 => 'Monica Turner',
    2 => 'Owner',
    3 => 'monicat52@aol.com',
    4 => 'Turner',
    5 => '0 to 3',
  ),
  33 => 
  array (
    0 => 'Patricia Oliver FCCH',
    1 => 'Patricia Oliver',
    2 => 'Owner',
    3 => 'oliverfcc@yahoo.com',
    4 => 'Dr. Seuss',
    5 => '0-3',
  ),
  34 => 
  array (
    0 => 'Lisa\'s Lil\' Wonders Childcare',
    1 => 'Lisa Dupree',
    2 => 'Owner',
    3 => 'ladyd0316@yahoo.com',
    4 => 'Lisa\'s Classroom',
    5 => 'Birth-3',
  ),
  35 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Nichola Griffiths-Butts',
    2 => 'Owner/Director/Educator',
    3 => 'nicholagriffiths@yahoo.com',
    4 => 'Nichola\'s classroom',
    5 => '0-3',
  ),
  36 => 
  array (
    0 => 'Bear Necessities FCCH',
    1 => 'Laconia Walker',
    2 => 'OWNER',
    3 => 'BEARNCTY@YAHOO.COM',
    4 => 'BNFDC28',
    5 => '1YR-2 1/2',
  ),
  37 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Jessica Thurmond',
    2 => 'teacher',
    3 => 'Jessicathurmond1@gmail.com',
    4 => 'Jessica Thurmond FCCH',
    5 => 'infants/tooddlers',
  ),
  38 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Destiny Daconcaicao',
    2 => 'teacher',
    3 => 'Dessjenkins@gmail.com',
    4 => 'Jessica Thurmond FCCH',
    5 => 'infants/tooddlers',
  ),
  39 => 
  array (
    0 => 'My Precious Lillie\'s FCCH',
    1 => 'Ezzieola (Izzieola) Jones',
    2 => 'Infant/Toddler Specialist',
    3 => 'mypreciouslillieshccf@gmail.com',
    4 => 'Lillie\'s',
    5 => 'Infant/Toddlers',
  ),
  40 => 
  array (
    0 => 'Smart Kids College FCCH',
    1 => 'Loretta Ferguson',
    2 => 'Infant/Toddler Specialist',
    3 => 'smartkidzcollege@gmail.com',
    4 => 'Big Bears',
    5 => 'Infant/Toddlers',
  ),
  41 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Fatima Flores',
    2 => 'Teacher',
    3 => 'Fatima.Flores@lsfnet.org',
    4 => 'EHS-A',
    5 => '0 -12 months',
  ),
  42 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Makeria Davis',
    2 => 'Teacher',
    3 => 'Makceria.Davis@lsfnet.org',
    4 => 'EHS-A',
    5 => '0-12 Months',
  ),
  43 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Samoy Grizzle',
    2 => 'Teacher',
    3 => 'Samoy.Grizzle@lsfnet.org',
    4 => 'EHS-B',
    5 => '2-3 year olds',
  ),
  44 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Johnnie Guyton',
    2 => 'Teacher',
    3 => 'Johnnie.guyton@lsfnet.org',
    4 => 'EHS-B',
    5 => '2-3 year olds',
  ),
  45 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Carlene Thornton',
    2 => 'Teacher',
    3 => 'Carlene.Thornton@lsfnet.org',
    4 => 'EHS-C',
    5 => '1-2  Year olds',
  ),
  46 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Alejandra Hernandez',
    2 => 'Teacher',
    3 => 'Alejandra.Hernandez@lsfnet.org',
    4 => 'EHS-C',
    5 => '1-2 year olds',
  ),
);


// === FILE 3: Child Roster ===
// Headers: Center Name | Child Name | Classroom Name | Age Group | Age Group for Assessment | Date of Birth | Gender | Ethnicity | Native Language

$child_roster_headers = array (
  0 => 'Center Name',
  1 => 'Child Name',
  2 => 'Classroom Name',
  3 => 'Age Group',
  4 => 'Age Group for Assessment',
  5 => 'Date of Birth',
  6 => 'Gender',
  7 => 'Ethnicity',
  8 => 'Native Language',
);

$child_roster_data = array (
  0 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Noah Curtis',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2025-04-01',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  1 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Olivia Howden',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2025-03-01',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  2 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kamryn Lowe',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2025-02-27',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  3 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jamar Murph Jr',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2024-11-24',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  4 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Fredwoobin Stinfort',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2024-10-28',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  5 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Chidley Baptiste',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2025-01-06',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  6 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ricayla Williams',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2025-04-08',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  7 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ricaylin Williams',
    2 => 'EHS A',
    3 => 'Infants',
    4 => '',
    5 => '2025-04-08',
    6 => 'female',
    7 => 'Black',
    8 => 'English',
  ),
  8 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Isai Garbo-Zarra',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-02-24',
    6 => 'Male',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  9 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Miyomi McClorin',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-08-13',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  10 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Brycen Moore',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-02-25',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  11 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Liam Navarette',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-05-10',
    6 => 'Male',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  12 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Blaize Reid',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-06-22',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  13 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Azaiah Reinhardt',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-03-14',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  14 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Zyraire Rejulus',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-05-18',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  15 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ryandy Thelemaque',
    2 => 'EHS B',
    3 => 'Toddler',
    4 => '',
    5 => '2024-05-14',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  16 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Marzell Ambrose- Huffman',
    2 => 'EHS C',
    3 => '2 year olds',
    4 => '',
    5 => '2023-10-05',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  17 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Gemma Dominique',
    2 => 'EHS C',
    3 => '2 year olds',
    4 => '',
    5 => '2023-10-30',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  18 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Gain Normil',
    2 => 'EHS C',
    3 => '2 year olds',
    4 => '',
    5 => '2023-12-15',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  19 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Syndly Boisrond',
    2 => 'EHS C',
    3 => '2 year olds',
    4 => '',
    5 => '2024-01-14',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  20 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Lyric Mosley',
    2 => 'EHS C',
    3 => '2 year olds',
    4 => '',
    5 => '2023-10-24',
    6 => 'Female',
    7 => 'Black',
    8 => 'EnglishJ',
  ),
  21 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jaymiahs Orius',
    2 => 'EHS C',
    3 => '2 year olds',
    4 => '',
    5 => '2023-11-15',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  22 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Lola Saunders',
    2 => 'EHS C',
    3 => '2 year olds',
    4 => '',
    5 => '2023-12-02',
    6 => '',
    7 => 'Black',
    8 => 'Creole',
  ),
  23 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Marsiah Ambrose- Huffman',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2023-10-05',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  24 => 
  array (
    0 => 'West Palm Beach',
    1 => 'K\'Myri Brown',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2023-07-21',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  25 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Micah Gabriel',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2023-09-05',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  26 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Maya Harvey',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2023-01-24',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  27 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Wayne Hightower Jr',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2023-03-12',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  28 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Elani Ladouceur',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2023-05-11',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  29 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Dakai Mickens',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2023-06-29',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  30 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Chrishante Ridgeway',
    2 => 'EHS D',
    3 => '2 year olds',
    4 => '',
    5 => '2022-12-22',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  31 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Afnan Bizante',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2022-12-21',
    6 => 'Female',
    7 => 'Indian',
    8 => 'English',
  ),
  32 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Dijonay Brown',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2023-03-08',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  33 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jah\'mir Brown',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2023-07-03',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  34 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Brayden Dorisma',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2023-01-06',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  35 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Loyal French',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2023-03-30',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  36 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Selena Maldonado',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2023-05-11',
    6 => 'Female',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  37 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Akyla Moore',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2022-12-03',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  38 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jonah Toussaint',
    2 => 'EHS E',
    3 => '2 year olds',
    4 => '',
    5 => '2022-11-25',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  39 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Semaj Brown',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2023-08-23',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  40 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kenji Clairjeune',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2023-01-07',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  41 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Wilskaicha Francois',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2023-02-13',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  42 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kaiden Hill',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2023-08-31',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  43 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Zuery Jean',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2023-05-20',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  44 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Amari Mangum',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2023-08-14',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  45 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Autumn Napier',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2023-09-03',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  46 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Reginald Thomas',
    2 => 'EHS F',
    3 => '2 year olds',
    4 => '',
    5 => '2022-12-08',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  47 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Isadora Charles',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2023-10-02',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  48 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Adassah Corrielan',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2023-01-01',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  49 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Phaith Exilas',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2023-08-21',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  50 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Skylar Henry',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2023-05-05',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  51 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Leah Joseph',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2022-11-25',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  52 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Aryya Leonard',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2023-07-22',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  53 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Joe\'l McCloud',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2023-03-07',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  54 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Malani Smith',
    2 => 'EHS G',
    3 => '2 year olds',
    4 => '',
    5 => '2023-06-10',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  55 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Messiah Ambrose- Huffman',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-04-03',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  56 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Aariyah Boucher',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-02-24',
    6 => 'Female',
    7 => 'Black',
    8 => 'EnglishK',
  ),
  57 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kaiser Cherubin',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-04-20',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  58 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Mapou Claude',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-03-20',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  59 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ja\'zya Cooley',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-04-21',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  60 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Peter Exilas',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-05-27',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  61 => 
  array (
    0 => 'West Palm Beach',
    1 => 'August Guillaume',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-08-17',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  62 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Sarah Johnson',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-05-10',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  63 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Antonio Kelly',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2021-12-27',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  64 => 
  array (
    0 => 'West Palm Beach',
    1 => 'A\'zariana Medina',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-06-15',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  65 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Naiara Metellus',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2021-10-07',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  66 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Malik Onescar',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-09-05',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  67 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Justin Souffrant',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-08-10',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  68 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Guivenchi Supreme',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2021-12-10',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  69 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Skylar Viard',
    2 => 'HS A',
    3 => '3 year olds',
    4 => '',
    5 => '2022-01-12',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  70 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Diesel Barahona',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-06-22',
    6 => 'Male',
    7 => 'White',
    8 => 'English',
  ),
  71 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Elodie McGilles',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-06-02',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  72 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Malakhi Cooke',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-08-10',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  73 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Nathanael Duclona',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-06-03',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  74 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jose Gelin',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-02-14',
    6 => 'Male',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  75 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Alisen Goureige',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-06-07',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  76 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Daisy Grandison',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-04-22',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  77 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Zylonnie Heath',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2021-10-23',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  78 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Aidan Jerome',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-08-15',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  79 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Matthew Lee',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-03-16',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  80 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Yood Marc',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-08-18',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  81 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Yara Marcelin',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-05-24',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  82 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Cyren McNeece',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2021-12-07',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  83 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Alani White',
    2 => 'HS B',
    3 => '3 year olds',
    4 => '',
    5 => '2022-03-07',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  84 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jaylain Berrette',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-09-17',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  85 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Cassidy Boswell',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-10-27',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  86 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Emelia Brown',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-11-22',
    6 => 'Female',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  87 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jayden Byrd',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-11-25',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  88 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ajay Cozart',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-12-30',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  89 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Elias Davis Morales',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-10-05',
    6 => 'Male',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  90 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Gianna Dominique',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-09-10',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  91 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Elisha Douarin',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-11-10',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  92 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Richie Etienne',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-09-28',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  93 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Leila Francois',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-10-27',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  94 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Widlens  Joseph Telfort',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-08-24',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  95 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Legacy McClorin',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-12-25',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  96 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Julanie Monchet',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-11-04',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'English',
  ),
  97 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Heaven Valcin',
    2 => 'HS C',
    3 => 'mixed 3s 4s',
    4 => '',
    5 => '2021-11-04',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  98 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Delaina Harris',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2020-09-17',
    6 => 'Female',
    7 => 'White',
    8 => 'English',
  ),
  99 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Nathaniel Baptiste',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2020-10-06',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  100 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jah\'nari Brown',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-09-01',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  101 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Isabella Charles',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-03-20',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  102 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Salif Cummings John Jr.',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2020-12-12',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  103 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Joao Demosthene',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-08-06',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  104 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Esther Dona',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-09-04',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  105 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jesse Gabriel',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-01-15',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  106 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ahmari Gilbert',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-01-04',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  107 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Celisa Johnson',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-06-07',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  108 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Amari Leonard',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-03-24',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  109 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Karissa Lisius',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-08-22',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  110 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Aleeyah Marbah',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2020-10-15',
    6 => 'Female',
    7 => 'Hispanic',
    8 => 'English',
  ),
  111 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jaynica Orius',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-07-13',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  112 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Sophia Pierre Meus',
    2 => 'HS D',
    3 => 'VPK',
    4 => '',
    5 => '2021-05-07',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  113 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Giovani Dominique',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2020-10-15',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  114 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Perlina Exilas',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2020-11-06',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  115 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Zyrrayah hilaire',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-09-01',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  116 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Tyrell Hinds Jr',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-04-16',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  117 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Amelia Jeffrey',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2020-10-27',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  118 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Amari Massillon',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-05-14',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  119 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Juni Monchet',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2020-09-02',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'English',
  ),
  120 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Celeste Navarette',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2020-09-21',
    6 => 'Female',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  121 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Saman munoz Restrepo',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-05-25',
    6 => 'Male',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  122 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Rique Otisme',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2020-12-11',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  123 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Rebecca Pierre',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-03-26',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  124 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Johnny Rejulus',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-03-21',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  125 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Lurnise Simeon',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-08-23',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  126 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Micheal Spears Jr',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2020-12-03',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  127 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Shunna Tenelus',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-05-09',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  128 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Noah Wilson',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-08-19',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  129 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Ily Wulfan',
    2 => 'HS E',
    3 => 'VPK',
    4 => '',
    5 => '2021-02-25',
    6 => 'Female',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  130 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Rose Kelly Azor',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-07-17',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  131 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Sireen Bizanti',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-04-30',
    6 => 'Female',
    7 => 'Indian',
    8 => 'English',
  ),
  132 => 
  array (
    0 => 'West Palm Beach',
    1 => 'River Coleman',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2020-09-17',
    6 => 'Female',
    7 => 'White',
    8 => 'English',
  ),
  133 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Brailyn Dennison',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2020-12-05',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  134 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Myline Edward',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-07-10',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  135 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kash Grant',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2020-12-01',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  136 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Markein Henderson',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-03-14',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  137 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jaylyn Henry',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2020-12-30',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  138 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Hadassa Hilliaire',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-01-07',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  139 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Zaharra Mackey',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-01-10',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  140 => 
  array (
    0 => 'West Palm Beach',
    1 => 'nyla natural Nacence',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-05-29',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  141 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Lutchano Prezeau',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-07-02',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  142 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jaylah Raheim',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-02-26',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  143 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Roodolph Registre',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2021-01-01',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  144 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Fedjina Stinfort',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2020-11-30',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  145 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Allison Valdes',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2020-10-23',
    6 => 'Female',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  146 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jayson Valmont',
    2 => 'HS F',
    3 => 'VPK',
    4 => '',
    5 => '2020-10-09',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  147 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kai Baker',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-06-10',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  148 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Dolph Casseus',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-07-26',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  149 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Kelly Dorvil',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-07-16',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  150 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jayden Eldine',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-04-05',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  151 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Harper Garcon',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-09-22',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  152 => 
  array (
    0 => 'West Palm Beach',
    1 => 'A\'layia Harmon',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2021-11-17',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  153 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jay jay Joseph',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2021-09-21',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  154 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Micah Lee',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-03-16',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  155 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Jeremiah Pierre',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-05-26',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  156 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Nalani Pinkney',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-01-05',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  157 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Alan Ramirez',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2021-12-17',
    6 => 'Male',
    7 => 'Hispanic',
    8 => 'Soanish',
  ),
  158 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Steve Saint  Natus',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-07-30',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  159 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Michael Sena',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-02-22',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  160 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Joy Verdrigue',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-10-07',
    6 => 'Female',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  161 => 
  array (
    0 => 'West Palm Beach',
    1 => 'Londyn Watson',
    2 => 'HS G',
    3 => '3 year olds',
    4 => '',
    5 => '2022-03-25',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  162 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Rulcy A.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2020-09-27',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  163 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Farid B.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-07-17',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  164 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Samantha C.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-01-06',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  165 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Anderson J.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-06-20',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  166 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Wilver L.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-04-19',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  167 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Camila L.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-06-04',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  168 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Keidy L.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-08-10',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  169 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Rodri L.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2020-12-28',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  170 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Kevin L.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2020-11-27',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  171 => 
  array (
    0 => 'Jupiter HS',
    1 => 'James M.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-06-01',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  172 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Dania M.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-04-10',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  173 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Alizon M.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2020-11-26',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  174 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Roman R.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-03-29',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  175 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Valentina S.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2021-02-27',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  176 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Judah T.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2020-12-31',
    6 => 'M',
    7 => 'Black',
    8 => 'English',
  ),
  177 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Dayra V.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2020-10-14',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  178 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Sofia V.',
    2 => 'HS-A',
    3 => 'Preschool',
    4 => '',
    5 => '2020-10-15',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  179 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Daniel  A.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-05-24',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  180 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Alison C',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-10-13',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  181 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Oneida C.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-01-14',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  182 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Erdogan D.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-05-16',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  183 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Kevin D.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-08-23',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  184 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Isabella L.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-11-23',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'English',
  ),
  185 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Keily L.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-02-25',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  186 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Anderson L.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-11-06',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  187 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Keyla L.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-11-27',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  188 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Gaia M.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-06-28',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  189 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Rodolfo M.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-11-03',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  190 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Edson R.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-07-10',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  191 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Lia R.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-07-10',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  192 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Khiren S.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2021-01-26',
    6 => 'M',
    7 => 'Black',
    8 => 'English',
  ),
  193 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Samara T.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-09-10',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  194 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Yeshua T',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-10-24',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  195 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Erick Z.',
    2 => 'HS-B',
    3 => 'Preschool',
    4 => '',
    5 => '2020-11-20',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  196 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Yaslin C.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2022-06-11',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  197 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Ema C.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2022-01-10',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  198 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Sophia',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-09-04',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  199 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Vilma G.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-10-09',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  200 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Oscar I.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-09-11',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  201 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Kimberly J.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2022-01-05',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  202 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Leah L.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2022-04-27',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  203 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Romina L.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-10-22',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  204 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Amori M.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-12-31',
    6 => 'F',
    7 => 'Black',
    8 => 'English',
  ),
  205 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Laura M.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-12-12',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  206 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Bartolo M.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-10-17',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  207 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Romeo R.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2022-06-27',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  208 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Alex S.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2021-10-12',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  209 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Emma S.',
    2 => 'HS-C',
    3 => 'Preschool',
    4 => '',
    5 => '2022-01-04',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  210 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Hawk A.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-01-18',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'English',
  ),
  211 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Amelia C.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-07-15',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  212 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Angeles C.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-09-11',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  213 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Katherine C.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-07-29',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  214 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Genesis E.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-06-08',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  215 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Matias L.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-05-14',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  216 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Yessi L.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2021-09-02',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  217 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Edison L.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-07-18',
    6 => 'M',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  218 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Amoni M.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2021-12-31',
    6 => 'F',
    7 => 'Black',
    8 => 'English',
  ),
  219 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Kayla M.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-05-24',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  220 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Luna P.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-08-26',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  221 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Kailani R.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2022-03-26',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  222 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Liam R.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2021-12-12',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  223 => 
  array (
    0 => 'Jupiter HS',
    1 => 'Eimy V.',
    2 => 'HS-D',
    3 => 'Preschool',
    4 => '',
    5 => '2021-09-25',
    6 => 'F',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  224 => 
  array (
    0 => 'Monica Turner FCCH',
    1 => 'Kahlynn Jones',
    2 => 'Turner',
    3 => '0 to 3',
    4 => '',
    5 => '2023-05-11',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  225 => 
  array (
    0 => 'Monica Turner FCCH',
    1 => 'Jenesis Shanchrz',
    2 => 'Turner',
    3 => '0 to 3',
    4 => '',
    5 => '2024-06-11',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  226 => 
  array (
    0 => 'Patricia Oliver FCCH',
    1 => 'K.J. P',
    2 => 'Dr. Seuss',
    3 => '2 yrs',
    4 => '',
    5 => '2023-10-25',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  227 => 
  array (
    0 => 'Patricia Oliver FCCH',
    1 => 'Charly T.',
    2 => 'Dr. Seuss',
    3 => '2 yrs',
    4 => '',
    5 => '2023-07-23',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  228 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Naomi P',
    2 => 'Lisa\'s Classroom',
    3 => 'Toddler',
    4 => '',
    5 => '2022-11-29',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  229 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Sam O',
    2 => 'Lisa\'s Classroom',
    3 => 'Toddler',
    4 => '',
    5 => '2023-03-18',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  230 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Hadassa J',
    2 => 'Lisa\'s Classroom',
    3 => 'Toddler',
    4 => '',
    5 => '2023-03-09',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  231 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Andy R',
    2 => 'Lisa\'s Classroom',
    3 => 'Toddler',
    4 => '',
    5 => '2023-04-29',
    6 => 'Male',
    7 => 'Hispanic',
    8 => 'Spanish',
  ),
  232 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Jhudsan F',
    2 => 'Lisa\'s Classroom',
    3 => 'Toddler',
    4 => '',
    5 => '2023-07-05',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  233 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Levi I',
    2 => 'Lisa\'s Classroom',
    3 => 'Toddler',
    4 => '',
    5 => '2023-02-14',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  234 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Nephtalie J',
    2 => 'Lisa\'s Classroom',
    3 => 'Infant',
    4 => '',
    5 => '2025-03-16',
    6 => 'Female',
    7 => 'Black',
    8 => 'Creole',
  ),
  235 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Clarissa T',
    2 => 'Lisa\'s Classroom',
    3 => 'Infant',
    4 => '',
    5 => '2025-02-03',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  236 => 
  array (
    0 => 'Lisa\'s Lil\' Wonder',
    1 => 'Guwensky L',
    2 => 'Lisa\'s Classroom',
    3 => 'Infant',
    4 => '',
    5 => '2024-06-12',
    6 => 'Male',
    7 => 'Black',
    8 => 'Creole',
  ),
  237 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Jatasia J',
    2 => 'Nichola\'s classroom',
    3 => '3',
    4 => '',
    5 => '2022-10-10',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  238 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Treveon N',
    2 => 'Nichola\'s classroom',
    3 => '3',
    4 => '',
    5 => '2022-10-19',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  239 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Khai B',
    2 => 'Nichola\'s classroom',
    3 => '2',
    4 => '',
    5 => '2022-11-16',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  240 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Solai J',
    2 => 'Nichola\'s classroom',
    3 => '2',
    4 => '',
    5 => '2023-07-28',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  241 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Harmony P',
    2 => 'Nichola\'s classroom',
    3 => '2',
    4 => '',
    5 => '2023-07-19',
    6 => 'Female',
    7 => 'Hispanic',
    8 => 'English',
  ),
  242 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Madison C',
    2 => 'Nichola\'s classroom',
    3 => '1',
    4 => '',
    5 => '2023-12-19',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  243 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Karsyn M',
    2 => 'Nichola\'s classroom',
    3 => '1',
    4 => '',
    5 => '2024-07-21',
    6 => 'Female',
    7 => 'Black',
    8 => 'English',
  ),
  244 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Giovanni M',
    2 => 'Nichola\'s classroom',
    3 => '1',
    4 => '',
    5 => '2024-10-23',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  245 => 
  array (
    0 => 'Nichola Griffiths-Butts FCCH',
    1 => 'Josiah A',
    2 => 'Nichola\'s classroom',
    3 => '0',
    4 => '',
    5 => '2025-04-11',
    6 => 'Male',
    7 => 'Black',
    8 => 'English',
  ),
  246 => 
  array (
    0 => 'Bear Necessities FCCH',
    1 => 'SARAI B',
    2 => 'BNFDC28',
    3 => '1.5',
    4 => '',
    5 => '2023-12-12',
    6 => 'Female',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  247 => 
  array (
    0 => 'Bear Necessities FCCH',
    1 => 'ISAIAH Y',
    2 => 'BNFDC28',
    3 => '2.5',
    4 => '',
    5 => '2022-12-03',
    6 => 'Male',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  248 => 
  array (
    0 => 'Bear Necessities FCCH',
    1 => 'ZARIAH H',
    2 => 'BNFDC28',
    3 => '2',
    4 => '',
    5 => '2023-07-01',
    6 => 'Female',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  249 => 
  array (
    0 => 'Bear Necessities FCCH',
    1 => 'NOAH M',
    2 => 'BNFDC28',
    3 => '1',
    4 => '',
    5 => '2024-09-20',
    6 => 'Male',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  250 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Youvensley F.',
    2 => 'Jessica Thurmond FCCH',
    3 => 'infants/toddlers',
    4 => '',
    5 => '2023-01-14',
    6 => 'Male',
    7 => 'non-hispanic',
    8 => 'English',
  ),
  251 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Alani G.',
    2 => 'Jessica Thurmond FCCH',
    3 => 'infants/toddlers',
    4 => '',
    5 => '2022-11-28',
    6 => 'female',
    7 => 'non-hispanic',
    8 => 'English',
  ),
  252 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Robentz T.',
    2 => 'Jessica Thurmond FCCH',
    3 => 'infants/toddlers',
    4 => '',
    5 => '2024-02-12',
    6 => 'Male',
    7 => 'non-hispanic',
    8 => 'English',
  ),
  253 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Wislene J.',
    2 => 'Jessica Thurmond FCCH',
    3 => 'infants/toddlers',
    4 => '',
    5 => '2023-06-30',
    6 => 'female',
    7 => 'non-hispanic',
    8 => 'English',
  ),
  254 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Abija F.',
    2 => 'Jessica Thurmond FCCH',
    3 => 'infants/toddlers',
    4 => '',
    5 => '2023-10-30',
    6 => 'female',
    7 => 'non-hispanic',
    8 => 'English',
  ),
  255 => 
  array (
    0 => 'Jessica Thurmond FCCH',
    1 => 'Leando P.',
    2 => 'Jessica Thurmond FCCH',
    3 => 'infants/toddlers',
    4 => '',
    5 => '2023-07-31',
    6 => 'Male',
    7 => 'non-hispanic',
    8 => 'English',
  ),
  256 => 
  array (
    0 => 'My Precious Lillie\'s HCCF',
    1 => 'Jayden Chrisostome',
    2 => 'Lillie\'s',
    3 => 'Toddler',
    4 => '',
    5 => '2022-11-23',
    6 => 'Male',
    7 => 'Haitian',
    8 => 'Creole',
  ),
  257 => 
  array (
    0 => 'My Precious Lillie\'s HCCF',
    1 => 'Liam Gallardo',
    2 => 'Lillie\'s',
    3 => 'Toddler',
    4 => '',
    5 => '2023-08-19',
    6 => 'Male',
    7 => 'Spanish',
    8 => 'Spanish',
  ),
  258 => 
  array (
    0 => 'My Precious Lillie\'s HCCF',
    1 => 'Rubi Morrison',
    2 => 'Lillie\'s',
    3 => 'Toddler',
    4 => '',
    5 => '2024-12-03',
    6 => 'Female',
    7 => 'African American',
    8 => 'English',
  ),
  259 => 
  array (
    0 => 'My Precious Lillie\'s HCCF',
    1 => 'Rylee Morrison',
    2 => 'Lillie\'s',
    3 => 'Infant',
    4 => '',
    5 => '2023-11-01',
    6 => 'Female',
    7 => 'African American',
    8 => 'English',
  ),
  260 => 
  array (
    0 => 'My Precious Lillie\'s HCCF',
    1 => 'Zhamari Neal',
    2 => 'Lillie\'s',
    3 => 'Toddler',
    4 => '',
    5 => '2023-11-14',
    6 => 'Male',
    7 => 'African American',
    8 => 'English',
  ),
  261 => 
  array (
    0 => 'Smart Kids College FCCH',
    1 => 'Evon Barrett',
    2 => 'Big Bears',
    3 => 'Toddler',
    4 => '',
    5 => '2023-11-04',
    6 => 'Male',
    7 => 'Black or African American',
    8 => 'English',
  ),
  262 => 
  array (
    0 => 'Smart Kids College FCCH',
    1 => 'Jakobe Hall',
    2 => 'Big Bears',
    3 => 'Toddler',
    4 => '',
    5 => '2023-06-10',
    6 => 'Male',
    7 => 'Black or African American',
    8 => 'English',
  ),
  263 => 
  array (
    0 => 'Smart Kids College FCCH',
    1 => 'Jakyn Hall',
    2 => 'Big Bears',
    3 => 'Toddler',
    4 => '',
    5 => '2024-11-28',
    6 => 'Male',
    7 => 'Black or African American',
    8 => 'English',
  ),
  264 => 
  array (
    0 => 'Smart Kids College FCCH',
    1 => 'Yohan Sidrac',
    2 => 'Big Bears',
    3 => 'Toddler',
    4 => '',
    5 => '2023-04-17',
    6 => 'Male',
    7 => 'Black or African American',
    8 => 'English',
  ),
  265 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Akila B',
    2 => 'EHS-A',
    3 => '1 YR',
    4 => '',
    5 => '2025-01-14',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  266 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Kai\'Ari C',
    2 => 'EHS-A',
    3 => '1YR 3 MONS',
    4 => '',
    5 => '2024-09-27',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  267 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Khase C',
    2 => 'EHS-A',
    3 => '1YR 3 MONS',
    4 => '',
    5 => '2024-09-27',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  268 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Donali J',
    2 => 'EHS-A',
    3 => '1 YR',
    4 => '',
    5 => '2025-01-16',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  269 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Denim T',
    2 => 'EHS-A',
    3 => '10 MONS',
    4 => '',
    5 => '2025-03-09',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  270 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'De\'Aria W',
    2 => 'EHS-A',
    3 => '1YRS',
    4 => '',
    5 => '2025-01-11',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  271 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Ahkeem A',
    2 => 'EHS-B',
    3 => '2yrs',
    4 => '',
    5 => '2023-10-15',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  272 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Demetrius C',
    2 => 'EHS-B',
    3 => '2YRS',
    4 => '',
    5 => '2023-08-04',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  273 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Aiden K',
    2 => 'EHS-B',
    3 => '2YRS',
    4 => '',
    5 => '2023-06-08',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  274 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Aubrey L',
    2 => 'EHS-B',
    3 => '3YRS',
    4 => '',
    5 => '2022-11-04',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  275 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Carson L',
    2 => 'EHS-B',
    3 => '2YRS',
    4 => '',
    5 => '2023-02-05',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  276 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Ah;Mari M',
    2 => 'EHS-B',
    3 => '3 YRS',
    4 => '',
    5 => '2022-12-28',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  277 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Ke\'Yani S',
    2 => 'EHS-B',
    3 => '2 YRS',
    4 => '',
    5 => '2023-03-30',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  278 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Diore T',
    2 => 'EHS-B',
    3 => '2YRS',
    4 => '',
    5 => '2023-12-17',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  279 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Amirion D',
    2 => 'EHS-C',
    3 => '2YRS',
    4 => '',
    5 => '2024-01-05',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  280 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Skylar D',
    2 => 'EHS-C',
    3 => '2YRS',
    4 => '',
    5 => '2024-01-24',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  281 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Stormi D',
    2 => 'EHS-C',
    3 => '2YRS',
    4 => '',
    5 => '2024-01-24',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  282 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Daniel L',
    2 => 'EHS-C',
    3 => '2YRS',
    4 => '',
    5 => '2024-01-02',
    6 => 'M',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  283 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Curtavious M',
    2 => 'EHS-C',
    3 => '1 YEAR',
    4 => '',
    5 => '2024-05-04',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
  284 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Layla S',
    2 => 'EHS-C',
    3 => '1 YR 10 MONTHS',
    4 => '',
    5 => '2024-03-30',
    6 => 'F',
    7 => 'Black',
    8 => 'SPANISH',
  ),
  285 => 
  array (
    0 => 'South Bay HS/EHS',
    1 => 'Jahki Spear',
    2 => 'EHS-C',
    3 => '1YRS',
    4 => '',
    5 => '2024-03-13',
    6 => 'F',
    7 => 'Black',
    8 => 'ENGLISH',
  ),
);

